import { NextResponse } from "next/server"
import type { FeedItem } from "@/types/movie"

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300))

  const feedItems: FeedItem[] = [
    {
      id: "feed-1",
      type: "collection_add",
      userId: "user-1",
      movieId: "1",
      createdAt: "2023-05-15T20:30:00Z",
      collections: ["Favorites", "Sci-Fi Classics"],
    },
    {
      id: "feed-2",
      type: "like",
      userId: "user-1",
      movieId: "2",
      createdAt: "2023-05-14T19:15:00Z",
    },
    {
      id: "feed-3",
      type: "watched_episode",
      userId: "user-1",
      movieId: "7",
      createdAt: "2023-05-13T21:00:00Z",
      season: 3,
      episode: 7,
      episodeTitle: "One Minute",
    },
    {
      id: "feed-4",
      type: "download_status",
      userId: "user-1",
      movieId: "1",
      createdAt: "2023-05-12T18:45:00Z",
      downloadStatus: "downloaded",
      size: 4200,
      quality: "4K HDR",
    },
    {
      id: "feed-5",
      type: "like",
      userId: "user-1",
      movieId: "4",
      createdAt: "2023-05-11T17:30:00Z",
    },
    {
      id: "feed-6",
      type: "watched_episode",
      userId: "user-1",
      movieId: "8",
      createdAt: "2023-05-10T16:15:00Z",
      season: 5,
      episode: 9,
      episodeTitle: "The Dance of Dragons",
    },
    {
      id: "feed-7",
      type: "collection_add",
      userId: "user-1",
      movieId: "5",
      createdAt: "2023-05-09T15:00:00Z",
      collections: ["Sci-Fi Classics", "90s Movies"],
    },
    {
      id: "feed-8",
      type: "download_status",
      userId: "user-1",
      movieId: "3",
      createdAt: "2023-05-08T14:45:00Z",
      downloadStatus: "paused",
      size: 5100,
      quality: "4K HDR",
    },
    {
      id: "feed-9",
      type: "watched_episode",
      userId: "user-1",
      movieId: "9",
      createdAt: "2023-05-07T13:30:00Z",
      season: 2,
      episode: 5,
      episodeTitle: "Dig Dug",
    },
    {
      id: "feed-10",
      type: "collection_add",
      userId: "user-1",
      movieId: "10",
      createdAt: "2023-05-06T12:15:00Z",
      collections: ["Sci-Fi", "Star Wars Universe"],
    },
    {
      id: "feed-11",
      type: "download_status",
      userId: "user-1",
      movieId: "7",
      createdAt: "2023-05-05T11:00:00Z",
      downloadStatus: "downloaded",
      size: 45000,
      quality: "1080p",
    },
    {
      id: "feed-12",
      type: "watched_episode",
      userId: "user-1",
      movieId: "10",
      createdAt: "2023-05-04T10:45:00Z",
      season: 2,
      episode: 8,
      episodeTitle: "The Rescue",
    },
    {
      id: "feed-13",
      type: "collection_add",
      userId: "user-1",
      movieId: "8",
      createdAt: "2023-05-03T09:30:00Z",
      collections: ["Fantasy", "Epic Series"],
    },
    {
      id: "feed-14",
      type: "download_status",
      userId: "user-1",
      movieId: "9",
      createdAt: "2023-05-02T08:15:00Z",
      downloadStatus: "deleted",
      size: 35000,
      quality: "1080p",
    },
    {
      id: "feed-15",
      type: "watched_episode",
      userId: "user-1",
      movieId: "7",
      createdAt: "2023-05-01T07:00:00Z",
      season: 3,
      episode: 6,
      episodeTitle: "Sunset",
    },
    {
      id: "feed-16",
      type: "collection_add",
      userId: "user-1",
      movieId: "4",
      createdAt: "2023-04-30T06:45:00Z",
      collections: ["Tarantino Films", "Classics"],
    },
    {
      id: "feed-17",
      type: "download_status",
      userId: "user-1",
      movieId: "10",
      createdAt: "2023-04-29T05:30:00Z",
      downloadStatus: "downloading",
      size: 28000,
      quality: "4K Dolby Vision",
    },
    {
      id: "feed-18",
      type: "watched_episode",
      userId: "user-1",
      movieId: "8",
      createdAt: "2023-04-28T04:15:00Z",
      season: 5,
      episode: 8,
      episodeTitle: "Hardhome",
    },
    {
      id: "feed-19",
      type: "collection_add",
      userId: "user-1",
      movieId: "2",
      createdAt: "2023-04-27T03:00:00Z",
      collections: ["Prison Movies", "Classics"],
    },
    {
      id: "feed-20",
      type: "like",
      userId: "user-1",
      movieId: "3",
      createdAt: "2023-04-26T02:45:00Z",
    },
  ]

  return NextResponse.json(feedItems)
}

